[package]
name = "bard"
version = "0.9.0-alpha"
authors = ["Vojtech Kral <vojtech@kral.hk>"]
description = "Creates PDF and HTML songbooks out of easy-to-write Markdown sources."
repository = "https://github.com/vojtechkral/bard"
homepage = "https://github.com/vojtechkral/bard"
license = "Apache-2.0"
keywords = ["music", "markdown"]
edition = "2018"

[lib]
name = "bard"
path = "src/lib.rs"

[[bin]]
name = "bard"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.26"
clap = "2.32"
colored = "2.0.0"
comrak = "0.10.0"
ctrlc = "3.1.3"
glob = "0.3"
handlebars = "3.5.3"
lazy_static = "1.4.0"
notify = "4.0.13"
regex = "1.4.5"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0.39"
thiserror = "1.0.14"
toml = "0.5"

[dev-dependencies]
assert-json-diff = "2.0.1"
