edition = "2018"
unstable_features = true

blank_lines_upper_bound = 2
fn_args_layout = "Compressed"
format_strings = true
imports_indent = "Visual"
overflow_delimited_expr = true
reorder_imports = false
reorder_modules = false
report_fixme = "Always"
use_field_init_shorthand = true
# wrap_comments = true  # screws up // to /* */, probably a bug in rustfmt
